services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_PORT=5432
      - DB_NAME=api8inf349
      - REDIS_URL=redis://redis:6379
      - FLASK_APP=api8inf349.py
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - db
      - redis
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  worker:
    build: .
    command: flask worker
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_PORT=5432
      - DB_NAME=api8inf349
      - REDIS_URL=redis://redis:6379
      - FLASK_APP=api8inf349.py
      - FLASK_ENV=development
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  pgdata: